# Generated by Django 5.1.5 on 2026-05-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffaccount_created_at_staffaccount_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(default='paid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('receiver_name', models.CharField(max_length=255)),
                ('from_address', models.TextField()),
                ('to_address', models.TextField()),
                ('sender_phone_num', models.CharField(max_length=15)),
                ('receiver_phone_num', models.CharField(max_length=15)),
                ('parcel_information', models.JSONField()),
                ('weight', models.PositiveIntegerField()),
                ('invoice_number', models.CharField(max_length=20)),
                ('freight', models.PositiveIntegerField(default=0)),
                ('loading_unloading', models.PositiveIntegerField(default=0)),
                ('door_pickup', models.PositiveIntegerField(default=0)),
                ('other_transport_crossing', models.PositiveIntegerField(default=0)),
                ('mamool', models.PositiveIntegerField(default=0)),
                ('statistical_charges', models.PositiveIntegerField(default=0)),
                ('door_delivery', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_type', models.CharField(choices=[('GoodDown Delivery', 'GoodDown Delivery'), ('Door Delivery', 'Door Delivery')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_couriers', to='staff.staffaccount')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_couriers', to='staff.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_couriers', to='staff.location')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier', to='staff.payment')),
            ],
        ),
    ]
