# Generated by Django 5.1.5 on 2026-05-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_payment_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('To Pay', 'To Pay')], default='Paid', max_length=20),
        ),
    ]
