# Generated by Django 5.1.5 on 2026-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_payment_mode_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='lr_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='short_code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
