# Generated by Django 5.1.5 on 2026-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_courier_lr_number_location_short_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=255)),
            ],
        ),
    ]
