# Generated by Django 5.1.5 on 2026-05-12 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_courier_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_path', models.JSONField(help_text='List of intermediate location names or IDs')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_routes', to='staff.driver')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_routes', to='staff.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_routes', to='staff.location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_routes', to='staff.vehicle')),
            ],
        ),
    ]
