# Generated by Django 5.1.5 on 2026-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_driver_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='status',
            field=models.CharField(choices=[('inplace', 'In Place'), ('shipping', 'Shipping'), ('delevered', 'delevered')], default='inplace', max_length=20),
        ),
    ]
