# Generated by Django 5.1.5 on 2026-05-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_courier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='staff.route'),
        ),
    ]
