# Generated by Django 5.1.5 on 2026-05-12 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_courier_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='GDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
                ('couriers', models.ManyToManyField(related_name='gdms', to='staff.courier')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdms', to='staff.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdms', to='staff.route')),
            ],
        ),
    ]
