# Generated by Django 5.1.5 on 2026-05-12 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_driver_phone_number_gdm'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_gdms', to='staff.staffaccount'),
        ),
        migrations.AddField(
            model_name='gdm',
            name='gdm_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
