# Generated by Django 5.1.5 on 2026-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_gdm_created_by_gdm_gdm_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdm',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('unshipped', 'Unshipped')], default='unshipped', max_length=20),
        ),
    ]
