# Generated by Django 5.1.5 on 2026-05-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_gdm_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='user_name',
            field=models.CharField(default='temp_driver', max_length=255),
            preserve_default=False,
        ),
    ]
