# Generated by Django 5.1.5 on 2026-05-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_remove_driver_user_remove_vehicle_driver_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdm',
            name='status',
        ),
    ]
