# Generated by Django 5.1.5 on 2026-05-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_gdm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='delevered_to_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('Online', 'Online')], default='None', max_length=20),
        ),
    ]
