# Generated by Django 5.1.5 on 2026-05-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_courier_delivered_to_customer_alter_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='courier',
            name='status',
            field=models.CharField(choices=[('inplace', 'In Place'), ('shipping', 'Shipping'), ('delevered', 'Delevered')], default='inplace', max_length=20),
        ),
    ]
