# Generated by Django 5.1.5 on 2026-05-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.PositiveIntegerField(default=0)),
                ('spent', models.PositiveIntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('expenses', models.ManyToManyField(blank=True, related_name='accounts', to='staff.expense')),
            ],
        ),
    ]
