# Generated by Django 5.1.5 on 2026-05-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='expenses',
        ),
        migrations.AddField(
            model_name='account',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='staff.staffaccount'),
            preserve_default=False,
        ),
    ]
