# Generated by Django 5.1.5 on 2026-05-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_remove_account_expenses_account_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='getting_person_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='getting_person_ph',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
